### ISSUE TITLE
New API only returns ranked matches

### ISSUE THREAD

**Issue by jzyrobert** [ForFunLabs/webapi#3]
Is this intended?

**Comment by oscarvazquez** [comment]
Intentional for now but still unsure if I'm going to leave it that way and have it only return ranked matches by default. 

The plan was to add a parameter for include unranked matches.

What do you guys think?

**Comment by oscarvazquez** [comment]
Added param to include unranked matches in result

**Comment by jzyrobert** [comment]
Nice, though maybe that should be the default? Or do people care about ranked more

**Comment by oscarvazquez** [comment]
Maybe it's the wrong assumption but I imagine these endpoints will be used mostly for statistical analysis and my guess would be users don't try as hard in unranked matches so it would muddy up the data a bit
